ServerEvents.tags("item", (event) => {
  event.add("mayview:logs", [
    "minecraft:dark_oak_log",
    "minecraft:oak_log",
    "minecraft:acacia_log",
    "minecraft:birch_log",
    "minecraft:jungle_log",
    "minecraft:spruce_log",
    "minecraft:mangrove_log",
    "minecraft:cherry_log",

    "cobblemon:apricorn_log",
    "cobblemon:saccharine_log",
    "cobblemon:saccharine_log_slathered",

    "cluttered:willow_log",
    "cluttered:flowering_willow_log",
    "cluttered:poplar_log",
    "cluttered:flowering_poplar_log",
    "cluttered:crabapple_log",
    "cluttered:flowering_crabapple_log",
    "cluttered:sycamore_log",
    "cluttered:fluorescent_maple_log",
    "cluttered:blue_mushroom_log",
    "cluttered:red_mushroom_log",

    "biomeswevegone:aspen_log",
    "biomeswevegone:baobab_log",
    "biomeswevegone:blue_enchanted_log",
    "biomeswevegone:cika_log",
    "biomeswevegone:cypress_log",
    "biomeswevegone:ebony_log",
    "biomeswevegone:fir_log",
    "biomeswevegone:green_enchanted_log",
    "biomeswevegone:holly_log",
    "biomeswevegone:ironwood_log",
    "biomeswevegone:jacaranda_log",
    "biomeswevegone:mahogany_log",
    "biomeswevegone:maple_log",
    "biomeswevegone:palm_log",
    "biomeswevegone:palo_verde_log",
    "biomeswevegone:pine_log",
    "biomeswevegone:rainbow_eucalyptus_log",
    "biomeswevegone:redwood_log",
    "biomeswevegone:sakura_log",
    "biomeswevegone:skyris_log",
    "biomeswevegone:spirit_log",
    "biomeswevegone:white_mangrove_log",
    "biomeswevegone:willow_log",
    "biomeswevegone:witch_hazel_log",
    "biomeswevegone:zelkova_log",

    "biomeswevegone:florus_stem",
    "biomeswevegone:spirit_roots",

    "expandeddelight:cinnamon_log",

    "minecraft:crimson_stem",
    "minecraft:crimson_hyphae",
    "minecraft:warped_stem",
    "minecraft:warped_hyphae",

    "culturaldelights:avocado_log",
  ]);
});
